from multiprocessing import Pool
from pathlib import Path

from fv3_runtime import log, report_missing_fixed_files, tmp_cwd
from fv3_state import state
from fv3_utils import cp, run_cmd


def _run_make_orog(
    c_res: int,
    tile: int,
    grid_dir: Path,
    out_dir: Path,
    orog_dir: Path,
    exec_dir: Path,
    lonb: int = None,
    latb: int = None,
    inputorog: Path = None,
    tmp: Path = None,
    local_state: dict = None,
):
    state.update(local_state)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    orog = exec_dir / "orog"

    log_file = state.logs / f"make_orog_tile_{tile}.log"

    # Decide grid type
    is_latlon = lonb is not None and latb is not None and c_res is None
    inorogexist = inputorog is not None

    # Workdir

    if is_latlon:
        workdir = tmp / "latlon" / "orog" / f"latlon_{lonb}x{latb}"
        orogfile = "none"
    else:
        workdir = tmp / f"C{c_res}" / "orog" / f"tile{tile}"
        orogfile = Path(inputorog).name if inorogexist else "none"

    workdir.mkdir(parents=True, exist_ok=True)

    # OUTGRID
    if is_latlon:
        out_grid = "none"
    else:
        out_grid = f"C{c_res}_grid.tile{tile}.nc"

    files = {
        orog_dir / "thirty.second.antarctic.new.bin": "fort.15",
        orog_dir / "landcover30.fixed": "landcover30.fixed",
        orog_dir / "gmted2010.30sec.int": "fort.235",
    }
    missing_files = [f for f in files if not f.exists()]
    if missing_files:
        report_missing_fixed_files(missing_files, sub_dir="orog")

    # Prepare working directory
    with tmp_cwd(workdir):
        for src, dst in files.items():
            cp(src, dst)

        if inorogexist:
            cp(inputorog, ".")

        if not is_latlon:
            cp(grid_dir / out_grid, ".")

        cp(orog, ".")

        # Input file
        mtnres, jcap, NR, NF1, NF2, efac, blat = 1, 0, 0, 0, 0, 0, 0
        with open("INPS", "w") as f:
            f.write(
                f"{mtnres} {lonb or c_res} {latb or c_res} {jcap} {NR} {NF1} {NF2} {efac} {blat}\n"
            )
            f.write(f"{out_grid}\n")
            f.write(f"{orogfile}\n")

        # Run executable
        with open("INPS", "r") as fin:
            cmd = [f"{orog}"]

            result, msgs = run_cmd(cmd, stdin=fin, stdout=log_file, stderr=log_file)

        if result != 0:
            log.error(msgs)
            raise RuntimeError(f"Failed to generate orography for tile: [{tile}]")

        # Output file
        if is_latlon:
            outfile = f"oro.{lonb}x{latb}.nc"
        else:
            outfile = f"oro.C{c_res}.tile{tile}.nc"

        cp("out.oro.nc", out_dir / outfile)


def run_make_orog(
    c_res: int,
    tiles: list[int],
    grid_dir: Path,
    out_dir: Path,
    orog_dir: Path,
    exec_dir: Path,
    lonb: int = None,
    latb: int = None,
    inputorog: Path = None,
    tmp: Path = None,
    mod_dir: Path = None,
):
    """
    Generate orography NetCDF files for FV3 cubed-sphere or lat-lon grids.

    This function wraps the `fv3_make_orog.sh` workflow, which produces
    FV3-compatible orography files using high-resolution static datasets such
    as GMTED2010 or GTOPO30. The resulting files are used for surface
    topography initialization in FV3-based models (e.g., UFS, GEFS, GFDL-FV3).

    Parameters
    ----------
    c_res : int or None
        Cubed-sphere resolution (e.g., 96 for a C96 grid). Required for
        global or nested cubed-sphere grids, not used for lat-lon grids.
    tiles : list[int] or None
        List of tile indices for the grid:
        - `1-6` for global cubed-sphere tiles
        - `7` for regional grids
    grid_dir : Path or None
        Directory containing the grid NetCDF files (e.g., `grid_tile*.nc`)
        generated by `make_hgrid`.
    out_dir : Path
        Directory in which the generated orography NetCDF files will be written.
    orog_dir : Path
        Directory containing high-resolution static orography and land-cover
        data (e.g., GMTED2010, USGS, or equivalent).
    exec_dir : Path
        Path to directory containing the `orog` executable or equivalent binary
        used to generate orography data.
    lonb, latb : int or None, optional
        Longitude and latitude dimensions (number of grid points) for
        latitude-longitude grids. Required only for `gtype='regional_esg'`
        or other structured-grid configurations.
    inputorog : Path or None, optional
        Optional user-supplied orography file. If provided, this file will be
        used directly instead of generating orography from static datasets.
    tmp : Path or None, optional
        Temporary working directory for intermediate files. Defaults to the
        system environment variable `$TMPDIR` if not provided.
    mod_dir : Path or None, optional
        Optional directory containing pre-generated orography files. If this
        directory exists, the function will copy its contents to `out_dir` and
        skip the orography generation process.
    """

    # check if mod_dir is presnt
    if mod_dir.exists() and len(list(mod_dir.glob("*"))) > 0:
        src = str(mod_dir).replace(str(state.work_dir), str(state.case_dir))
        log.info(f"Using existing orography files from {src}")
        files_to_copy = list(mod_dir.glob("*"))
        for file in files_to_copy:
            cp(file, out_dir / file.name)
        return

    args = [
        (
            c_res,
            tile,
            grid_dir,
            out_dir,
            orog_dir,
            exec_dir,
            lonb,
            latb,
            inputorog,
            tmp,
            dict(state),
        )
        for tile in tiles
    ]

    with Pool(processes=len(args)) as pool:
        pool.starmap(_run_make_orog, args)
