import os
from multiprocessing import Pool
from pathlib import Path

from fv3gfs_runtime import log
from fv3gfs_state import state
from fv3gfs_utils import cp, run_cmd


def _run_make_orog(
    res: int | None,
    tile: int | None,
    grid_dir: Path | None,
    out_dir: Path,
    orog_dir: Path,
    exec_dir: Path,
    lonb: int | None = None,
    latb: int | None = None,
    inputorog: Path | None = None,
    tmp: Path | None = None,
    local_state: dict = None,
):
    state.update(local_state)

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    orog = exec_dir / "orog"

    log_file = state.logs / f"make_orog_tile_{tile}.log"

    # Decide grid type
    is_latlon = lonb is not None and latb is not None and res is None
    inorogexist = inputorog is not None

    # Workdir

    if is_latlon:
        workdir = tmp / "latlon" / "orog" / f"latlon_{lonb}x{latb}"
        orogfile = "none"
    else:
        workdir = tmp / f"C{res}" / "orog" / f"tile{tile}"
        orogfile = Path(inputorog).name if inorogexist else "none"

    workdir.mkdir(parents=True, exist_ok=True)

    # OUTGRID
    if is_latlon:
        out_grid = "none"
    else:
        out_grid = f"C{res}_grid.tile{tile}.nc"

    # Prepare working directory
    os.chdir(workdir)

    cp(orog_dir / "thirty.second.antarctic.new.bin", "fort.15")
    cp(orog_dir / "landcover30.fixed", ".")
    cp(orog_dir / "gmted2010.30sec.int", "fort.235")

    if inorogexist:
        cp(inputorog, ".")

    if not is_latlon:
        cp(grid_dir / out_grid, ".")

    cp(orog, ".")

    # Input file
    mtnres, jcap, NR, NF1, NF2, efac, blat = 1, 0, 0, 0, 0, 0, 0
    with open("INPS", "w") as f:
        f.write(
            f"{mtnres} {lonb or res} {latb or res} {jcap} {NR} {NF1} {NF2} {efac} {blat}\n"
        )
        f.write(f"{out_grid}\n")
        f.write(f"{orogfile}\n")

    log.debug("Running orog with INPS:")
    log.debug(Path("INPS").read_text())

    # Run executable
    with open("INPS", "r") as fin:
        cmd = [f"{orog}"]

        result, msgs = run_cmd(cmd, stdin=fin, log_file=log_file)

    if result != 0:
        log.error(msgs)
        raise RuntimeError(f"Failed to generate orography for tile: [{tile}]")

    # Output file
    if is_latlon:
        outfile = f"oro.{lonb}x{latb}.nc"
    else:
        outfile = f"oro.C{res}.tile{tile}.nc"

    cp("out.oro.nc", out_dir / outfile)


def run_make_orog(
    res: int | None,
    tiles: list[int] | None,
    grid_dir: Path | None,
    out_dir: Path,
    orog_dir: Path,
    exec_dir: Path,
    lonb: int | None = None,
    latb: int | None = None,
    inputorog: Path | None = None,
    tmp: Path | None = None,
):
    """
    Generate orography NetCDF files for FV3 cubed-sphere or lat-lon grids.

    This function wraps the `fv3gfs_make_orog.sh` workflow, which produces
    FV3-compatible orography files using high-resolution static datasets such
    as GMTED2010 or GTOPO30. The resulting files are used for surface
    topography initialization in FV3-based models (e.g., UFS, GEFS, GFDL-FV3).

    Parameters
    ----------
    res : int or None
        Cubed-sphere resolution (e.g., 96 for a C96 grid). Required for
        global or nested cubed-sphere grids, not used for lat-lon grids.
    tiles : list[int] or None
        List of tile indices for the grid:
        - `1-6` for global cubed-sphere tiles
        - `7` for regional grids
    grid_dir : Path or None
        Directory containing the grid NetCDF files (e.g., `grid_tile*.nc`)
        generated by `make_hgrid`.
    out_dir : Path
        Directory in which the generated orography NetCDF files will be written.
    orog_dir : Path
        Directory containing high-resolution static orography and land-cover
        data (e.g., GMTED2010, USGS, or equivalent).
    exec_dir : Path
        Path to directory containing the `orog` executable or equivalent binary
        used to generate orography data.
    lonb, latb : int or None, optional
        Longitude and latitude dimensions (number of grid points) for
        latitude-longitude grids. Required only for `gtype='regional_esg'`
        or other structured-grid configurations.
    inputorog : Path or None, optional
        Optional user-supplied orography file. If provided, this file will be
        used directly instead of generating orography from static datasets.
    tmp : Path or None, optional
        Temporary working directory for intermediate files. Defaults to the
        system environment variable `$TMPDIR` if not provided.
    """

    args = [
        (
            res,
            tile,
            grid_dir,
            out_dir,
            orog_dir,
            exec_dir,
            lonb,
            latb,
            inputorog,
            tmp,
            dict(state),
        )
        for tile in tiles
    ]

    with Pool(processes=len(args)) as pool:
        pool.starmap(_run_make_orog, args)
