
# sbatch.sh - Script to submit a job to SLURM with the appropriate environment variables

EXPORT_VARS="ALL,\
SBATCH_TIME_LIMIT=${SBATCH_TIME_LIMIT},\
SBATCH_PARTITION=${SBATCH_PARTITION},\
SBATCH_NTASKS_PER_NODE=${SBATCH_NTASKS_PER_NODE},\
SBATCH_NTASKS=${SBATCH_NTASKS},\
SBATCH_NNODES=${SBATCH_NNODES},\
SBATCH_MULTI_NODE_FLAG=${SBATCH_MULTI_NODE_FLAG},\
SBATCH_MEMORY_FLAG=${SBATCH_MEMORY_FLAG},\
SBATCH_NODE_EXCLUSIVE_FLAG=${SBATCH_NODE_EXCLUSIVE_FLAG},\
SBATCH_NODE_CONSTRAINT_FLAG=${SBATCH_NODE_CONSTRAINT_FLAG},\
SBATCH_CPUS_PER_TASK=${SBATCH_CPUS_PER_TASK},\
CONTAINER_BINDPATH="$CONTAINER_BINDPATH",\
CONTAINERS_DIR=${CONTAINERS_DIR},\
UFS_UTILS_DIR=${UFS_UTILS_DIR},\
SHIELD_ROOT_DIR=${SHIELD_ROOT_DIR},\
SCRATCH_DIR=${SCRATCH_DIR},\
JOBTMP_DIR=${JOBTMP_DIR},\
FIX_DIR=${FIX_DIR},\
ARCHIVE_ROOT_DIR=${ARCHIVE_ROOT_DIR},\
SHIELD_SIF=${SHIELD_SIF},\
PREPROCESS_SIF=${PREPROCESS_SIF},\
FREGRID_SIF=${FREGRID_SIF},\
CASE_PWD=${CASE_PWD},\
CASE_LOG_FILE=${CASE_LOG_FILE},\
CASE_ENSEMBLE_ID=${CASE_ENSEMBLE_ID},\
CASE_DATA_SYMLINK=${CASE_DATA_SYMLINK},\
CASE_RUN_START_TIME=${CASE_RUN_START_TIME},\
CASE_ROOT_DIR=${CASE_ROOT_DIR},\
CASE_PARENT_DIR=${CASE_PARENT_DIR},\
CASE_NAME=${CASE_NAME},\
CASE_RESUBMIT_INDEX=${CASE_RESUBMIT_INDEX},\
CASE_RESUBMIT_MAX=${CASE_RESUBMIT_MAX},\
CASE_ENSEMBLES=${CASE_ENSEMBLES},\
CASE_ARCHIVE=${CASE_ARCHIVE}"


JOB_ID=$(sbatch --parsable \
$SBATCH_NODE_EXCLUSIVE_FLAG \
$SBATCH_NODE_CONSTRAINT_FLAG \
$SBATCH_MEMORY_FLAG \
--time=$SBATCH_TIME_LIMIT \
--job-name=$SLURM_JOB_NAME \
--nodes=$SBATCH_NNODES \
--ntasks=$SBATCH_NTASKS \
--cpus-per-task=$SBATCH_CPUS_PER_TASK \
--ntasks-per-node=$SBATCH_NTASKS_PER_NODE \
--partition=$SBATCH_PARTITION \
--output=/dev/null \
--open-mode=$SLURM_OPEN_MODE \
--export="$EXPORT_VARS" \
"$UFS_UTILS_DIR/drivers/case_run.sh")


EXIT_CODE=$?
export EXIT_CODE