cloud_diagnosis_nml:
  reiflag: 4
  reimax: 150.0
  reimin: 10.0
  rewmax: 10.0
  rewmin: 5.0

fv_core_nml:
  RF_fast: true
  a_imp: 1.0
  adjust_dry_mass: false
  beta: 0.0
  consv_am: false
  consv_te: 0.0
  d2_bg: 0.0
  d2_bg_k1: 0.2
  d2_bg_k2: 0.1
  d4_bg: 0.15
  d_con: 1.0
  d_ext: 0.0
  dddmp: 0.5
  delt_max: 0.002
  dnats: 1
  do_vort_damp: true
  dwind_2d: false
  external_ic: true
  fill: true
  fill_dp: true
  fv_debug: false
  fv_sg_adj: 600
  gfs_phil: false
  hord_dp: -5
  hord_mt: 5
  hord_tm: 5
  hord_tr: -5
  hord_vt: 5
  hydrostatic: false
  ke_bg: 0.0
  kord_mt: 9
  kord_tm: -9
  kord_tr: 9
  kord_wz: 9
  make_nh: true
  mountain: false
  nord: 3
  nudge_qv: true
  nwat: 6
  p_fac: 0.05
  phys_hydrostatic: false
  range_warn: true
  reset_eta: false
  rf_cutoff: 3000.0
  sg_cutoff: 20000.0
  tau: 5.0
  tau_h2o: 0.0
  use_hydro_pressure: false
  vtdm4: 0.06
  warm_start: false
  z_tracer: true

gfdl_mp_nml:
  c_paut: 0.5
  c_pgacs: 0.01
  c_psaci: 0.05
  ccn_l: 300.0
  ccn_o: 100.0
  const_vg: false
  const_vi: false
  const_vr: false
  const_vs: false
  do_cond_timescale: true
  do_qa: true
  do_sedi_heat: false
  do_sedi_w: true
  dw_land: 0.15
  dw_ocean: 0.1
  fix_negative: true
  icloud_f: 0
  irain_f: 0
  prog_ccn: false
  qi0_crt: 0.00008
  qi_lim: 1.0
  ql_mlt: 0.002
  qs0_crt: 0.003
  qs_mlt: 0.000001
  rad_graupel: true
  rad_rain: true
  rad_snow: true
  rh_inc: 0.2
  rh_inr: 0.3
  rthresh: 0.00001
  tau_i2s: 1000.0
  tau_l2v: 300.0
  tau_v2l: 90.0
  vg_max: 16.0
  vi_max: 1.0
  vr_max: 16.0
  vs_max: 2.0
  z_slope_ice: true
  z_slope_liq: true

gfs_physics_nml:
  do_deep: false
  do_ocean: true
  imfdeepcnv: 2
  imfshalcnv: 2
  shal_cnv: true
  iaer: 111
  c0s_shal: 0.01
  c1_shal: 0.005
  cal_pre: false
  cdmbgwd: [ 0.0, 0.0 ]
  cloud_gfdl: true
  cnvcld: false
  cnvgwd: false
  debug: false
  dspheat: true
  fhcyc: 24.0
  fhlwr: 1800.0
  fhswr: 1800.0
  fhzero: 3.0
  hybedmf: true
  ialb: 1
  ico2: 2
  iems: 1
  isatmedmf: 1
  isol: 2
  isot: 1
  isubc_lw: 2
  isubc_sw: 2
  ivegsrc: 1
  ldiag3d: true
  lwhtr: true
  ncld: 5
  nst_anl: true
  pdfcld: false
  pre_rad: false
  prslrd0: 0.0
  random_clds: false
  redrag: true
  satmedmf: false
  swhtr: true
  trans_trac: true
  use_ufo: true
  xkzminv: 0.0
  zhao_mic: false
  sfc_coupled: true
  lsm: 2
