global:
    external_model: GFS
    convert_atm: true
    convert_sfc: true
    convert_nst: false

tileX:
  external_models:
    - external_model: HRRR
      convert_atm: true
      convert_sfc: false
      convert_nst: false

    - external_model: GFS
      convert_atm: false
      convert_sfc: true
      convert_nst: false

    


