# machine_config.yaml
paths:
  jobtmp: /jobtmp/$USER/gfdl_shield
  scratch: /oscar/scratch/$USER/models/gfdl_shield
  case_root: /oscar/scratch/$USER/models/gfdl_shield/runs
  fix_dir: /oscar/data/deeps/shared/gfdl_shield/fix
  ufs_utils: /oscar/data/deeps/shared/gfdl_shield/ufs_py
  shield: /oscar/data/deeps/shared/gfdl_shield/containers/shield.sif
  fregrid: /oscar/data/deeps/shared/gfdl_shield/containers/fregrid.sif
  preprocess: /oscar/data/deeps/shared/gfdl_shield/containers/preprocess.sif
  shield_root: /oscar/data/deeps/shared/gfdl_shield
  archive_root: $HOME/data/$USER/data/models/gfdl_shield/archive
  containers_root: /oscar/data/deeps/shared/gfdl_shield/containers
  container_bindpath: ["/oscar", "/sss", "/users", "/jobtmp"]

modules: ["hpcx-mpi", "netcdf-mpi", "libyaml", "netcdf"]
launchers:
  srun:
    ["srun", "--mpi=pmix", "--distribution=block:block", "--cpu-bind=cores -n"]
  mpirun: ["mpirun", "-np"]
