
# sbatch.sh - Script to submit a job to SLURM with the appropriate environment variables


EXPORT_VARS="ALL,\
SBATCH_TIME=${SBATCH_TIME},\
SBATCH_PARTITION=${SBATCH_PARTITION},\
SBATCH_NTASKS_PER_NODE=${SBATCH_NTASKS_PER_NODE},\
SBATCH_NTASKS=${SBATCH_NTASKS},\
SBATCH_NNODES=${SBATCH_NNODES},\
SBATCH_MULTI_NODE=${SBATCH_MULTI_NODE},\
SBATCH_MEMORY_FLAG=${SBATCH_MEMORY_FLAG},\
SBATCH_NODE_EXCLUSIVE_FLAG=${SBATCH_NODE_EXCLUSIVE_FLAG},\
SBATCH_NODE_CONSTRAINT_FLAG=${SBATCH_NODE_CONSTRAINT_FLAG},\
SBATCH_CPUS_PER_TASK=${SBATCH_CPUS_PER_TASK},\
CONTAINERS_DIR=${CONTAINERS_DIR},\
CONTAINER_BINDPATH="$CONTAINER_BINDPATH",\
UFS_UTILS=${UFS_UTILS},\
SHIELD_SIF=${SHIELD_SIF},\
SHIELD_ROOT=${SHIELD_ROOT},\
SCRATCH=${SCRATCH},\
RUN_DIR=${RUN_DIR},\
RESUBMIT_COUNT=${RESUBMIT},\
PREPROCESS_SIF=${PREPROCESS_SIF},\
N_ENSEMBLES=${N_ENSEMBLES},\
LOG_FILE=${LOG_FILE},\
JOB_TMP=${JOB_TMP},\
FREGRID_SIF=${FREGRID_SIF},\
FIX_DIR=${FIX_DIR},\
ENSEMBLE_ID=${ENSEMBLE_ID},\
DATA_SYMLINK=${DATA_SYMLINK},\
CASE_RUN_START_TIME=${CASE_RUN_START_TIME},\
CASE_ROOT=${CASE_ROOT},\
CASE_PARENT_DIR=${CASE_PARENT_DIR},\
CASE_NAME=${CASE_NAME},\
ARCHIVE_ROOT=${ARCHIVE_ROOT},\
ARCHIVE_DATA=${ARCHIVE_DATA}"

JOB_ID=$(sbatch --parsable \
$SBATCH_NODE_EXCLUSIVE_FLAG \
$SBATCH_NODE_CONSTRAINT_FLAG \
$SBATCH_MEMORY_FLAG \
--time=$SBATCH_TIME \
--job-name=$SLURM_JOB_NAME \
--nodes=$SBATCH_NNODES \
--ntasks=$SBATCH_NTASKS \
--cpus-per-task=$SBATCH_CPUS_PER_TASK \
--ntasks-per-node=$SBATCH_NTASKS_PER_NODE \
--partition=$SBATCH_PARTITION \
--output=/dev/null \
--open-mode=$SLURM_OPEN_MODE \
--export="$EXPORT_VARS" \
"$UFS_UTILS/case_run.sh")


EXIT_CODE=$?
export EXIT_CODE